In [15]:
import numpy as np

In [16]:
np.array([10, 20, 24, 5, 15, 50,])

array([10, 20, 24,  5, 15, 50])

In [17]:
a = np.array([10, 30, 20, 4, 30, 51, 7, 2, 4, 40, 100])
a[4]

30

In [18]:
a[3:]

array([  4,  30,  51,   7,   2,   4,  40, 100])

In [19]:
a[3:7]

array([ 4, 30, 51,  7])

In [20]:
a[1::4]

array([30, 51, 40])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
type(ones)

function

In [31]:
from numpy import ones

type(ones[3])

TypeError: 'function' object is not subscriptable

In [32]:
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [34]:
b = np.array([['x', 'y', 'z'],['a', 'b', 'c']])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'b' 'c']]


numpy.ndarray

In [35]:
b.ndim

2

In [39]:
c = [12, 4, 10, 40, 2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [41]:
cabeceras = [('nombre', 'S10'), ('edad', int)]
datos = [('Juan', 10), ('Maria', 70),('Javier', 42), ('Samuel', 15)]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

In [42]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
np.arange(5, 30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [45]:
np.full((3, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [46]:
np.diag([0,3 ,9, 10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])